keywords = {
    'activate',
    'activates',
    'activated',
    'activator',
    'induce',
    'induces',
    'induced',
    'impair',
    'impairs',
    'impaired',
    'inhibit',
    'inhibits',
    'inhibitors',
    'inhibitor',
    'inhibited',
    'promote',
    'promotes',
    'promoted',
    'localize',
    'localizes',
    'localized',
    'lead',
    'leads',
    'leading',
    'enhance',
    'enhances',
    'enhancing',
    'enhanced',
    'stabilizes',
    'stabilize',
    'stabilized',
    'agonist',
    'increase',
    'increases',
    'increased',
    'mediate',
    'mediates',
    'mediator',
    'execute',
    'executes',
    'executed',
    'causes',
    'cause',
    'caused',
    'inactivate',
    'inactivates',
    'inactivated',
    'block',
    'blocks',
    'blocked',
    'repress',
    'repressed',
    'represses',
    'reduce',
    'reduces',
    'reduced',
    'disrupt',
    'disrupts',
    'disrupted',
    'prevent',
    'prevents',
    'prevented',
    'contribute',
    'contributes',
    'contributed',
    'participate',
    'participates',
    'participated',
    'antagonist'
}

positive_kw = {
    'activates',
    'activate',
    'activated',
    'induces',
    'induce',
    'induced',
    'promotes',
    'promote',
    'promoted',
    'localizes',
    'localized',
    'localize',
    'leading',
    'lead',
    'leads',
    'enhances',
    'enhance',
    'enhancing',
    'enhanced',
    'activator',
    'stabilizes',
    'stabilize',
    'stabilized',
    'increase',
    'increases',
    'increased',
    'mediates',
    'mediate',
    'mediator',
    'executes',
    'execute',
    'causes',
    'cause',
    'executed',
    'caused',
    'participates',
    'contributes',
    'contributed',
    'participate',
    'contribute',
    'participated'
}

inverse_keywords = {
    'activate': 'activated by',
    'activates': 'activated by',
    'activated': 'activated by',
    'activator': 'activated by',
    'induce': 'induced by',
    'induces': 'induced by',
    'induced': 'induced by',
    'impair': 'impaired by',
    'impairs': 'impaired by',
    'impaired': 'impaired by',
    'inhibit': 'inhibited by',
    'inhibits': 'inhibited by',
    'inhibitors': 'inhibited by',
    'inhibitor': 'inhibited by',
    'inhibited': 'inhibited by',
    'promote': 'promoted by',
    'promotes': 'promoted by',
    'promoted': 'promoted by',
    'localize': "localized by",
    'localizes': "localized by",
    'localized': "localized by",
    'lead': 'lead by',
    'leads': 'lead by',
    'leading': 'lead by',
    'enhance': 'enhanced by',
    'enhances': 'enhanced by',
    'enhancing': 'enhanced by',
    'enhanced': 'enhanced by',
    'stabilizes': 'stabilized by',
    'stabilize': 'stabilized by',
    'stabilized': 'stabilized by',
    'agonist': 'agonized by',
    'increase': 'increased by',
    'increases': 'increased by',
    'increased': 'increased by',
    'mediate': 'mediated by',
    'mediates': 'mediated by',
    'mediator': 'mediated by',
    'execute': 'executed by',
    'executes': 'executed by',
    'executed': 'executed by',
    'causes': 'caused by',
    'cause': 'caused by',
    'caused': 'caused by',
    'inactivate': 'inactivated by',
    'inactivates': 'inactivated by',
    'inactivated': 'inactivated by',
    'block': 'blocked by',
    'blocks': 'blocked by',
    'blocked': 'blocked by',
    'repress': 'repressed by',
    'repressed': 'repressed by',
    'represses': 'repressed by',
    'reduce': 'reduced by',
    'reduces': 'reduced by',
    'reduced': 'reduced by',
    'disrupt': 'disrupted by',
    'disrupts': 'disrupted by',
    'disrupted': 'disrupted by',
    'prevent': 'prevented by',
    'prevents': 'prevented by',
    'prevented': 'prevented by',
    'contribute': 'contributed to by',
    'contributes': 'contributed to by',
    'contributed': 'contributed to by',
    'participate': 'participated by',
    'participates': 'participated by',
    'participated': 'participated by',
    'antagonist': 'antagonized by'
}